#!/bin/bash
#
# This is an entrypoint that runs the MySQL server in the 'master' mode.
#
source ${CONTAINER_SCRIPTS_PATH}/common.sh
set -eu

[ -f ${CONTAINER_SCRIPTS_PATH}/validate_replication_variables.sh ] && . ${CONTAINER_SCRIPTS_PATH}/validate_replication_variables.sh
[ -f ${CONTAINER_SCRIPTS_PATH}/validate_variables.sh ] && . ${CONTAINER_SCRIPTS_PATH}/validate_variables.sh

# The 'server-id' for master needs to be constant

export MYSQL_SERVER_ID=$(server_id)
echo "The 'master' server-id is ${MYSQL_SERVER_ID}"

# Process the MySQL configuration files
envsubst < ${CONTAINER_SCRIPTS_PATH}/my-base.cnf.template > /etc/my.cnf.d/base.cnf
envsubst < ${CONTAINER_SCRIPTS_PATH}/my-paas.cnf.template > /etc/my.cnf.d/paas.cnf
#envsubst < ${CONTAINER_SCRIPTS_PATH}/my-master.cnf.template > /etc/my.cnf.d/master.cnf
envsubst < ${CONTAINER_SCRIPTS_PATH}/my-master-mm.cnf.template > /etc/my.cnf.d/master-mm.cnf
envsubst < ${CONTAINER_SCRIPTS_PATH}/my-repl-gtid.cnf.template > /etc/my.cnf.d/repl-gtid.cnf

init_db="NO";

if [ ! -d "$MYSQL_DATADIR/mysql" ]; then
  initialize_database "$@"
  init_db="YES";
else
  start_local_mysql "$@"
  init_db="NO";
fi

[ -f ${CONTAINER_SCRIPTS_PATH}/passwd-change.sh ] && . ${CONTAINER_SCRIPTS_PATH}/passwd-change.sh

echo Granting privileges
# Setup the 'master' replication on the MySQL server
mysql $mysql_flags <<EOSQL
  GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_MASTER_USER}'@'%' IDENTIFIED BY '${MYSQL_MASTER_PASSWORD}';
  FLUSH PRIVILEGES;
EOSQL

#mysql $mysql_flags <<EOSQL
#   INSERT INTO mysql.user (Host,User) values ('%','haproxy_check'); 
#   FLUSH PRIVILEGES;
#EOSQL


if [ "$init_db" == "YES" ] ; then
  echo waiting peer master to start up
  #wait_for_target_mysql_master
  sleep 5
  echo setup master-master;
  mysql $mysql_flags <<EOSQL
    CHANGE MASTER TO MASTER_HOST='${MYSQL_TARGET_MASTER_SERVICE_HOST}',MASTER_USER='${MYSQL_MASTER_USER}', MASTER_PASSWORD='${MYSQL_MASTER_PASSWORD}', MASTER_AUTO_POSITION = 1;
EOSQL
fi

[ -f ${CONTAINER_SCRIPTS_PATH}/post-init.sh ] && . ${CONTAINER_SCRIPTS_PATH}/post-init.sh

echo finishing up
# Restart the MySQL server with public IP bindings
mysqladmin $admin_flags flush-privileges shutdown
unset_env_vars
exec ${MYSQL_PREFIX}/libexec/mysqld --defaults-file=$MYSQL_DEFAULTS_FILE "$@" 2>&1
